import logging
import re
from typing import Awaitable, Callable, Optional

from openai import AsyncOpenAI

from bot.config import settings
from bot.utils.fake_progress import FractionCallback, run_with_fake_progress
from bot.utils.text_chunking import SENTENCE_BOUNDARIES, split_long_text

logger = logging.getLogger(__name__)

client = AsyncOpenAI(api_key=settings.OPENAI_API_KEY)

ProgressCallback = Callable[[int, int], Awaitable[None]]

# Chunk-size budget. Russian text is ~2.5 chars/token — 8000 chars ≈ 3200 input
# tokens, leaving ample room under gpt-4o's 16k output cap for the formatted
# response to roughly match input length without truncation.
FORMATTER_CHUNK_CHARS = 8000
FORMATTER_CHUNK_MAX_TOKENS = 6000

# Title is a separate, cheap call with a tiny output window. Sample = head +
# tail of the raw transcript so the model can see both the announced topic and
# any closing recap, without sending the whole thing.
TITLE_MAX_TOKENS = 80
TITLE_SAMPLE_HEAD_CHARS = 4000
TITLE_SAMPLE_TAIL_CHARS = 2000

SYSTEM_PROMPT = """\
Ты — помощник, который оформляет сырой текст транскрибации аудио/видео в читаемый вид.

Задачи:
1. Придумай короткий заголовок материала (до ~80 символов), отражающий содержание.
2. Обязательно разбей текст на смысловые абзацы. Даже если входной текст пришёл одним сплошным куском без переносов строк — всё равно раздели его по смыслу (смена темы, новая мысль, длинная пауза, новая реплика). Плоская стена текста недопустима.
3. Если в тексте видны признаки диалога, интервью или подкаста с двумя и более участниками (смена говорящих, вопрос-ответ, приветствия и представления, обращения по имени, реплики через «—») — ОБЯЗАТЕЛЬНО размечай реплики префиксом с именем или ролью спикера на той же строке, что и реплика. Если имена явно звучат в тексте (представление, обращение) — используй их. Иначе используй «Спикер 1», «Спикер 2» и т.д. В сомнительных случаях лучше пометь спикеров, чем оставь без меток. Если это точно монолог одного человека — не ставь никаких префиксов.
4. Сохрани исходный язык и смысл. Не придумывай фактов, не сокращай, не перефразируй.

Строгие правила форматирования вывода:
- Только чистый plain text. Никакого Markdown (`*`, `_`, `#`, `` ` ``), никаких HTML-тегов (`<b>`, `<i>` и т.п.).
- Не используй символы `<`, `>`, `&` как разметку. Если они встречаются в самом тексте — оставь как есть, но не добавляй новые.
- Первая строка — сам текст заголовка без каких-либо префиксов (не «Заголовок: …», не «Title: …», просто текст заголовка).
- После заголовка — одна пустая строка.
- Абзацы разделяй одной пустой строкой.
- Если есть спикеры — каждая реплика начинается с `<Имя или Спикер N>: ` на той же строке, что и текст реплики.

Если подсказка по источнику приходит как `Source: ...` — используй её как контекст для заголовка, но не копируй её как есть, если она нечитаемая (хэш, uuid и т.п.). Подсказка также может указывать на то, что это подкаст или интервью — тогда особенно внимательно ищи смену говорящих.
"""

# Used for chunked path: formats one fragment, must NOT emit a title (title is
# generated by a separate call over the whole transcript).
CHUNK_SYSTEM_PROMPT = """\
Ты — помощник, который оформляет сырой фрагмент транскрибации аудио/видео в читаемый вид.

Это один из нескольких фрагментов длинной транскрипции. Заголовок ты НЕ добавляешь — он уже сгенерирован отдельно. Возвращай только оформленное тело фрагмента, БЕЗ первой строки-заголовка и БЕЗ пустой строки перед телом.

Задачи:
1. Разбей текст фрагмента на смысловые абзацы. Плоская стена текста недопустима.
2. Если в тексте видны признаки диалога, интервью или подкаста — размечай реплики префиксом с именем или ролью спикера на той же строке, что и реплика (например, `Иван: ...`). Если имена звучат в тексте — используй их. Иначе — «Спикер 1», «Спикер 2» и т.д. В монологе — без префиксов.
3. Сохрани исходный язык и смысл. Не придумывай, не сокращай, не перефразируй.

Строгие правила форматирования:
- Только чистый plain text. Никакого Markdown, никаких HTML-тегов.
- Не добавляй заголовок. Не добавляй служебных комментариев типа «Фрагмент 1:», «Продолжение:» и т.п.
- Абзацы разделяй одной пустой строкой.
- Если есть спикеры — каждая реплика на отдельной строке с префиксом `<Имя или Спикер N>: `.
"""

# Used for chunks 2..N: carries forward the speaker labels established by the
# first chunk so labeling stays consistent across chunk boundaries.
CONTINUATION_SYSTEM_PROMPT = """\
Ты — помощник, который оформляет сырой фрагмент транскрибации аудио/видео в читаемый вид.

Это ПРОДОЛЖЕНИЕ уже начатой транскрипции. Заголовок НЕ добавляй. Строго соблюдай уже использованные метки спикеров (если они переданы в блоке `Метки спикеров:` в user-message) — один и тот же голос должен иметь одну и ту же метку от фрагмента к фрагменту.

Задачи:
1. Разбей текст фрагмента на смысловые абзацы.
2. Если передан список меток спикеров — используй ТОЛЬКО их для тех же голосов. Если появляется действительно новый голос, которого не было раньше, — добавь его как следующий номер «Спикер N+1».
3. Сохрани исходный язык и смысл. Не придумывай, не сокращай.

Строгие правила форматирования:
- Только чистый plain text. Никакого Markdown, никаких HTML-тегов.
- Не добавляй заголовок. Не добавляй служебных комментариев.
- Абзацы разделяй одной пустой строкой.
- Если есть спикеры — каждая реплика на отдельной строке с префиксом `<Имя или Спикер N>: `.
"""

TITLE_SYSTEM_PROMPT = """\
Ты — помощник, который придумывает короткий заголовок для расшифровки аудио/видео.

По предоставленному сэмплу материала (начало + конец транскрипции, опционально — подсказка по источнику) верни ТОЛЬКО строку заголовка — до ~80 символов, без кавычек, без префиксов («Заголовок:», «Title:»), без точки в конце. Заголовок должен отражать суть разговора/материала, а не пересказывать отдельные фразы.

Если подсказка источника нечитаема (хэш, uuid, случайный идентификатор) — игнорируй её и опирайся только на содержание.
"""


# Matches ``Speaker label: `` at the start of a line. Cyrillic/Latin letters,
# digits, spaces, dots, hyphens are allowed in the label itself; the label is
# capped at 40 chars to avoid accidentally matching a sentence that happens to
# contain a colon.
_SPEAKER_LABEL_RE = re.compile(r"(?m)^([^\n:]{1,40}?):\s", re.UNICODE)


def _build_user_message(raw_text: str, filename_hint: Optional[str]) -> str:
    if filename_hint:
        return f"Source: {filename_hint}\n\nТранскрибация:\n{raw_text}"
    return f"Транскрибация:\n{raw_text}"


def _build_chunk_user_message(chunk_text: str, filename_hint: Optional[str]) -> str:
    parts = []
    if filename_hint:
        parts.append(f"Source: {filename_hint}")
    parts.append(f"Фрагмент транскрибации:\n{chunk_text}")
    return "\n\n".join(parts)


def _build_continuation_user_message(
    chunk_text: str,
    filename_hint: Optional[str],
    speaker_labels: list[str],
) -> str:
    parts = []
    if filename_hint:
        parts.append(f"Source: {filename_hint}")
    if speaker_labels:
        labels = ", ".join(speaker_labels)
        parts.append(
            "Метки спикеров из предыдущих фрагментов: "
            f"{labels}. Используй те же метки для тех же голосов."
        )
    parts.append(f"Фрагмент транскрибации (продолжение):\n{chunk_text}")
    return "\n\n".join(parts)


def _build_title_user_message(raw_text: str, filename_hint: Optional[str]) -> str:
    head = raw_text[:TITLE_SAMPLE_HEAD_CHARS]
    tail = (
        raw_text[-TITLE_SAMPLE_TAIL_CHARS:]
        if len(raw_text) > TITLE_SAMPLE_HEAD_CHARS + TITLE_SAMPLE_TAIL_CHARS
        else ""
    )
    parts = []
    if filename_hint:
        parts.append(f"Source: {filename_hint}")
    if tail:
        parts.append(f"Начало транскрипции:\n{head}")
        parts.append(f"Конец транскрипции:\n{tail}")
    else:
        parts.append(f"Транскрипция:\n{head}")
    return "\n\n".join(parts)


def _extract_speaker_labels(formatted_text: str) -> list[str]:
    """Collect unique speaker labels (``Name:`` / ``Спикер N:``) from formatted text.

    Preserves insertion order so the first-mentioned speaker stays first.
    """
    seen: list[str] = []
    for match in _SPEAKER_LABEL_RE.finditer(formatted_text):
        label = match.group(1).strip()
        # Filter out obvious false positives (e.g. sentences with mid-word
        # colons, URL-like `http:`).
        if not label or label.lower() in {"http", "https", "ftp"}:
            continue
        if label not in seen:
            seen.append(label)
    return seen


async def _call_openai_raw(
    system_prompt: str,
    user_message: str,
    *,
    max_tokens: Optional[int] = None,
):
    kwargs = {
        "model": settings.GPT_MODEL,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message},
        ],
        "temperature": 0.2,
    }
    if max_tokens is not None:
        kwargs["max_tokens"] = max_tokens
    return await client.chat.completions.create(**kwargs)


def _content_and_finish(response) -> tuple[str, str]:
    choice = response.choices[0]
    content = (choice.message.content or "").strip()
    finish = choice.finish_reason or ""
    return content, finish


async def _call_openai_single(raw_text: str, filename_hint: Optional[str]) -> str:
    """Single-call path (short transcripts). Returns full formatted text with title.

    Raises ``RuntimeError`` on truncation so the caller can fall back to raw.
    """
    response = await _call_openai_raw(
        SYSTEM_PROMPT,
        _build_user_message(raw_text, filename_hint),
    )
    content, finish = _content_and_finish(response)
    if finish != "stop":
        raise RuntimeError(
            f"format_transcript: single-call truncated (finish_reason={finish!r}, "
            f"input_chars={len(raw_text)})"
        )
    return content


async def _generate_title(raw_text: str, filename_hint: Optional[str]) -> str:
    response = await _call_openai_raw(
        TITLE_SYSTEM_PROMPT,
        _build_title_user_message(raw_text, filename_hint),
        max_tokens=TITLE_MAX_TOKENS,
    )
    content, _finish = _content_and_finish(response)
    # Sanitize: strip wrapping quotes, trailing period, accidental markdown.
    title = content.strip().strip('"').strip("'").rstrip(".")
    # Defensive: collapse any newlines the model might have added.
    title = " ".join(title.split())
    return title


async def _format_chunk(
    chunk_text: str,
    *,
    system_prompt: str,
    user_message: str,
) -> str:
    """Format one chunk with one retry on any failure (incl. length-truncation).

    Raises ``RuntimeError`` if it fails after the retry.
    """
    last_error: Optional[Exception] = None
    for attempt in (1, 2):
        try:
            response = await _call_openai_raw(
                system_prompt,
                user_message,
                max_tokens=FORMATTER_CHUNK_MAX_TOKENS,
            )
            content, finish = _content_and_finish(response)
            if finish != "stop":
                raise RuntimeError(
                    f"chunk truncated (finish_reason={finish!r}, "
                    f"chunk_chars={len(chunk_text)})"
                )
            return content
        except Exception as e:  # noqa: BLE001 — we retry any transient failure
            last_error = e
            logger.warning(
                "format_chunk attempt %d failed: %s", attempt, e
            )
    assert last_error is not None
    raise RuntimeError("format_chunk: retry exhausted") from last_error


async def _format_chunked(
    raw_text: str,
    chunks: list[str],
    filename_hint: Optional[str],
    on_progress: Optional[ProgressCallback],
) -> str:
    """Format N>=2 chunks: separate title call + per-chunk formatting + join."""
    total_steps = len(chunks) + 1  # +1 for the title call

    async def report(done: int) -> None:
        if on_progress is not None:
            try:
                await on_progress(done, total_steps)
            except Exception:
                logger.exception("on_progress callback failed")

    await report(0)

    # Title — failures here fall back to filename_hint, don't abort the flow.
    try:
        title = await _generate_title(raw_text, filename_hint)
    except Exception:
        logger.exception("title generation failed; falling back to filename hint")
        title = (filename_hint or "").strip()
    await report(1)

    # First chunk — establishes speaker labels for the whole transcript.
    formatted_parts: list[str] = []
    first_formatted = await _format_chunk(
        chunks[0],
        system_prompt=CHUNK_SYSTEM_PROMPT,
        user_message=_build_chunk_user_message(chunks[0], filename_hint),
    )
    formatted_parts.append(first_formatted)
    speaker_labels = _extract_speaker_labels(first_formatted)
    await report(2)

    # Subsequent chunks — carry forward speaker labels.
    for i, chunk in enumerate(chunks[1:], start=2):
        part = await _format_chunk(
            chunk,
            system_prompt=CONTINUATION_SYSTEM_PROMPT,
            user_message=_build_continuation_user_message(
                chunk, filename_hint, speaker_labels
            ),
        )
        formatted_parts.append(part)
        await report(i + 1)

    body = "\n\n".join(formatted_parts)
    if title:
        return f"{title}\n\n{body}"
    return body


async def format_transcript(
    raw_text: str,
    filename_hint: Optional[str] = None,
    on_progress_fraction: Optional[FractionCallback] = None,
    on_progress: Optional[ProgressCallback] = None,
) -> str:
    """Post-process a raw Whisper transcript: add title, paragraphs, speaker labels.

    * Short inputs → single GPT call (fast path).
    * Long inputs → split by sentence boundaries, separate title call, per-chunk
      formatting with speaker-label continuity, join with blank lines.
    * On ANY unrecoverable failure → return ``raw_text`` unchanged (bot flow
      must not break on a formatting error).
    """
    if not raw_text.strip():
        return raw_text

    chunks = split_long_text(
        raw_text,
        max_chars=FORMATTER_CHUNK_CHARS,
        overlap_chars=0,
        prefer_boundaries=SENTENCE_BOUNDARIES,
    )

    # Single-chunk (short input) path — keep the original fake-progress UX.
    if len(chunks) <= 1:
        try:
            if on_progress_fraction is None:
                return await _call_openai_single(raw_text, filename_hint)
            expected_seconds = max(3.0, len(raw_text) / 2000)
            return await run_with_fake_progress(
                _call_openai_single(raw_text, filename_hint),
                on_progress_fraction,
                expected_seconds,
            )
        except Exception:
            logger.exception("format_transcript (single-call) failed; returning raw text")
            return raw_text

    # Multi-chunk path — real progress via on_progress, no fake-progress bar.
    try:
        return await _format_chunked(raw_text, chunks, filename_hint, on_progress)
    except Exception:
        logger.exception(
            "format_transcript (chunked) failed; returning raw text "
            "(chunks=%d, raw_chars=%d)",
            len(chunks),
            len(raw_text),
        )
        return raw_text
